// Generated by scripts/build-site.js for the static review site.
export const CONFIG = {
    mode: 'static',
    tokenUrl: "https://cas-bim-token.karthikeya-civ.workers.dev",
    publicUrl: "https://gitaecllmdev.github.io/cas-bim-web-viewer-2/",
    stateUrl: "",
    hitsUrl: "https://cas-bim-token.karthikeya-civ.workers.dev/hits?site=v2",
};
